# Generated by Django 4.1.7 on 2023-04-20 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_color',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_desc',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_long_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_short_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_text_color',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_url',
        ),
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='station',
            name='json_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='station',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='stop_id',
        ),
        migrations.AddField(
            model_name='station',
            name='station_id',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.RemoveField(
            model_name='station',
            name='user',
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
