# Generated by Django 4.1.7 on 2023-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_route_agency_id_remove_route_is_favorite_and_more'),
    ]

    operations = [
    ]
