# Generated by Django 4.1.7 on 2023-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_route_id_station_id_alter_route_route_id_and_more'),
    ]

    operations = [
    ]
