# Generated by Django 4.1.7 on 2023-04-26 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_route_id_alter_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
