# Generated by Django 4.1.7 on 2023-04-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_route_timeadded_station_timeadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='station',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
