# Generated by Django 4.1.7 on 2023-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_route_id_alter_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(max_length=10),
        ),
    ]
