# Generated by Django 4.1.7 on 2023-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_route_route_id_alter_station_station_id'),
    ]

    operations = [
    ]
